import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Loading } from "@/components/Loading";
import { Main } from "@/components/Main";
import { Providers } from "@/components/Providers";
import { Inter } from 'next/font/google';
import { Suspense } from "react";
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <body>
                <Providers>
                    <Header />
                    <Main>
                        <Suspense fallback={<Loading />}>
                            {children}
                        </Suspense>
                    </Main>
                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
