import './globals.css'
import {Inter} from 'next/font/google'
import {Header} from "@/app/Header";
import {Footer} from "@/app/Footer";
import {Suspense} from "react";
import Loading from "@/app/loading";
import {Main} from "@/app/Main";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
        <body>
        <Header/>
        <Main>
            <Suspense fallback={<Loading/>}>
                {children}
            </Suspense>
        </Main>
        <Footer/>
        </body>
        </html>
    )
}
