# Generated by Django 4.2.1 on 2023-05-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='management.subject', verbose_name='やる教科'),
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(blank=True, max_length=400, verbose_name='テキスト'),
        ),
    ]
