# Generated by Django 4.2.1 on 2023-05-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_school'),
        ('accounts', '0005_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.school', verbose_name='学校'),
        ),
    ]
