services:
  next:
    container_name: next
    image: node:20.2.0-bullseye-slim
    command: sh -c "npm run dev"
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    working_dir: /app
    environment:
#      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"

  django:
    container_name: django
    build: ./containers/django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      FRONTEND_URL: http://localhost:3000
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

volumes:
  front_node_modules:
  db-data:
