# Generated by Django 4.2.1 on 2023-05-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教科')),
            ],
            options={
                'verbose_name': '教科',
                'verbose_name_plural': '教科',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限'), (7, '7限'), (8, '8限')])),
                ('date', models.DateField()),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='student_name', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '授業',
                'verbose_name_plural': '授業',
            },
        ),
    ]
