# Generated by Django 4.2.1 on 2023-05-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_lesson_student_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '授業', 'verbose_name_plural': '授業'},
        ),
    ]
