import './globals.css'
import {Inter} from 'next/font/google'
import {Header} from "@/front/components/Header";
import {Footer} from "@/front/components/Footer";
import {Suspense} from "react";
import {Loading} from "@/front/components/Loading";
import {Main} from "@/front/components/Main";
import {Providers} from "@/front/components/Providers";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="ja">
        <body>
        <Providers>
        <Header/>
        <Main>
            <Suspense fallback={<Loading/>}>
                {children}
            </Suspense>
        </Main>
        <Footer/>
        </Providers>
        </body>
        </html>
    )
}
